### ISSUE TITLE
复现效果不好

### ISSUE THREAD

**Issue by leezy18** [wjfu99/MIA-LLMs#1]
您好，我参照您的代码进行复现，其中我只对读取数据部分进行了修改，因为我使用的数据是从huggingface下载到本地的。我微调的模型是gpt-2，使用的数据集是AgNews，超参数都是按照您给出的，我最后复现出来的结果AUC最好情况只有0.51。我想知道您论文中的0.949是如何实现的，谢谢
数据读取部分的代码修改如下：
`

    # train_dataset = datasets.load_dataset(
    #     args.dataset_name,
    #     args.dataset_config_name,
    #     split=f"train[:{int((1-args.validation_split_percentage)*100)}%]"
    # )
    # valid_dataset = datasets.load_dataset(
    #     args.dataset_name,
    #     args.dataset_config_name,
    #     split=f"train[{int((1-args.validation_split_percentage)*100)}%:]",
    # )
    # 假设 train-00000-of-00001.parquet 文件的路径已知
    train_file_path = f"{args.dataset_path}/train-00000-of-00001.parquet"

    # 确保文件存在
    if not os.path.exists(train_file_path):
        raise FileNotFoundError("Parquet file not found.")

    # 从 Parquet 文件加载整个数据集
    raw_dataset = Dataset.from_parquet(train_file_path)

    # 确定分割点
    num_validation_samples = int(len(raw_dataset) * args.validation_split_percentage)
    num_train_samples = len(raw_dataset) - num_validation_samples

    # 分割数据集为训练集和验证集
    train_dataset = raw_dataset.select(range(num_train_samples))
    valid_dataset = raw_dataset.select(range(num_train_samples, num_train_samples + num_validation_samples))

`

**Comment by wjfu99** [comment]
盲猜可能GPT-2没用full finetuning，使用PEFT在GPT-2这种小模型上可能导致性能不佳

**Comment by dooohow** [comment]
> 您好，我参照您的代码进行复现，其中我只对读取数据部分进行了修改，因为我使用的数据是从huggingface下载到本地的。我微调的模型是gpt-2，使用的数据集是AgNews，超参数都是按照您给出的，我最后复现出来的结果AUC最好情况只有0.51。我想知道您论文中的0.949是如何实现的，谢谢 数据读取部分的代码修改如下： `
> 
> ```
> # train_dataset = datasets.load_dataset(
> #     args.dataset_name,
> #     args.dataset_config_name,
> #     split=f"train[:{int((1-args.validation_split_percentage)*100)}%]"
> # )
> # valid_dataset = datasets.load_dataset(
> #     args.dataset_name,
> #     args.dataset_config_name,
> #     split=f"train[{int((1-args.validation_split_percentage)*100)}%:]",
> # )
> # 假设 train-00000-of-00001.parquet 文件的路径已知
> train_file_path = f"{args.dataset_path}/train-00000-of-00001.parquet"
> 
> # 确保文件存在
> if not os.path.exists(train_file_path):
>     raise FileNotFoundError("Parquet file not found.")
> 
> # 从 Parquet 文件加载整个数据集
> raw_dataset = Dataset.from_parquet(train_file_path)
> 
> # 确定分割点
> num_validation_samples = int(len(raw_dataset) * args.validation_split_percentage)
> num_train_samples = len(raw_dataset) - num_validation_samples
> 
> # 分割数据集为训练集和验证集
> train_dataset = raw_dataset.select(range(num_train_samples))
> valid_dataset = raw_dataset.select(range(num_train_samples, num_train_samples + num_validation_samples))
> ```
> 
> `

我用了full fine-tuning，复现效果也不太好，只有0.65左右的AUC

**Comment by dooohow** [comment]
> 盲猜可能GPT-2没用full finetuning，使用PEFT在GPT-2这种小模型上可能导致性能不佳

我在full finetuning下的效果也不理想，想问问是不是有什么默认参数设置的原因。但我看论文中的参数设置基本都作为超参数可以保持一致的

**Comment by wjfu99** [comment]
Please conside using the [GPT-2-XL (1.5B)](https://huggingface.co/openai-community/gpt2-xl) as mentioned in the original paper. The link of GPT-2 model provided in the README is misleading as pointed in #3, we will correct it later.
